spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://host.docker.internal:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      auto-commit: false
  #      maximum-pool-size: 10
  #      minimum-idle: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  sql:
    init:
      mode: always

server:
  error:
    include-message: always